[package]
name = "nchash-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nchash_rs"
crate-type = ["cdylib"]

[dependencies]
netcdf = "0.10.5"
num = "0.4.3"
pyo3 = "0.23.3"
